version: 0.9.0.{build}
image: WMF 5
environment:
  NugetApiKey:
    secure: jj4Njj2C9hl07VITV8LV12bMwAajCfimGpJDw/+G3JOMvhaecVb+6ldz9LvnVPvs
install:
- ps: >-
    Write-Host 'Installing NuGet PackageProvider'

    $pkg = Install-PackageProvider -Name NuGet -Force -ErrorAction Stop

    Write-Host "Installed NuGet version '$($pkg.version)'"

    Install-Module InvokeBuild -Force

    Install-Module Pester -Force

    Install-Module BuildHelpers -Force
build_script:
- ps: >-
    Invoke-Build -File .\PendingReboot.Build.ps1

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Release\testResults*.xml))
